[book]
title = "Hệ quản trị CSDL với Oracle"
authors = ["Nguyễn Phồn Lữa"]
language = "en"

[output.html]
additional-css = ["custom.css"]
site-url = "/dbms-with-oracle/"

[output.html.print]
enable = false
